name: Build pde basis

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build 
      run: clang++ -std=c++20 -O3 -g -fsanitize=address -fno-omit-frame-pointer pdebasis.c -o gcnn_asan

    - name: Run the program
      run: ./gcnn_asan 

    - name: Upload Artifact
      uses: actions/upload-artifact@v4 # Use the latest version
      with:
        name: segmentation 
        path: segmentation_output.png